### Login as a client
POST {{host}}/auth/login
Content-Type: application/json

{
  "email": "{{clientEmail}}",
  "password": "{{clientPassword}}"
}

### Login as a manager
POST {{host}}/auth/login
Content-Type: application/json

{
  "email": "{{managerEmail}}",
  "password": "{{managerPassword}}"
}

> {%
  client.global.set("accessToken", response.body['accessToken']);
  client.global.set("refreshToken", response.body['refreshToken'])
%}

### Get current cart
GET {{host}}/carts
Authorization: Bearer {{accessToken}}

### Adding item to cart
PATCH {{host}}/carts
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
  "products": [
    {
      "productId": 1,
      "quantity": 1
    }
  ]
}

### Adding item to cart
DELETE {{host}}/carts
Authorization: Bearer {{accessToken}}
Content-Type: application/json

### Complete the order using the current cart
POST {{host}}/carts
Authorization: Bearer {{accessToken}}
Content-Type: application/json

### Delte current cart
DELETE {{host}}/carts
Authorization: Bearer {{accessToken}}
