### Login as a client
POST {{host}}/auth/login
Content-Type: application/json

{
  "email": "{{clientEmail}}",
  "password": "{{clientPassword}}"
}

> {%
  client.global.set("accessToken", response.body['accessToken']);
  client.global.set("refreshToken", response.body['refreshToken'])
%}


### Login as a manager
POST {{host}}/auth/login
Content-Type: application/json

{
  "email": "{{managerEmail}}",
  "password": "{{managerPassword}}"
}

> {%
  client.global.set("accessToken", response.body['accessToken']);
  client.global.set("refreshToken", response.body['refreshToken'])
%}

### Get all orders of the current user
GET {{host}}/orders
Authorization: Bearer {{accessToken}}

### Get all orders of the specified user
GET {{host}}/orders/3
Authorization: Bearer {{accessToken}}
