### Login as a client
POST {{host}}/auth/login
Content-Type: application/json

{
  "email": "{{clientEmail}}",
  "password": "{{clientPassword}}"
}

### Login as a manager
POST {{host}}/auth/login
Content-Type: application/json

{
  "email": "{{managerEmail}}",
  "password": "{{managerPassword}}"
}

> {%
  client.global.set("accessToken", response.body['accessToken']);
  client.global.set("refreshToken", response.body['refreshToken'])
%}

### List all products
GET {{host}}/products?limit=2&cursor=220
Authorization: Bearer {{accessToken}}

### Search products by category
GET {{host}}/products/search?q=product&category=205