### Register a new user
POST {{host}}/auth/register
Content-Type: application/json

{
  "email": "{{$random.email}}",
  "password": "{{$random.alphabetic(6)}}"
}

### Login as a client
POST {{host}}/auth/login
Content-Type: application/json

{
  "email": "{{clientEmail}}",
  "password": "{{clientPassword}}"
}

### Login as a manager
POST {{host}}/auth/login
Content-Type: application/json

{
  "email": "{{managerEmail}}",
  "password": "{{managerPassword}}"
}

> {%
  client.global.set("accessToken", response.body['accessToken']);
  client.global.set("refreshToken", response.body['refreshToken'])
%}

### Get information about the current user
GET {{host}}/auth/me
Authorization: Bearer {{accessToken}}

### Add a single image to product
POST {{host}}/products/1/images
Content-Type: multipart/form-data; boundary=boundary
Authorization: Bearer {{ accessToken }}

--boundary
Content-Disposition: form-data; name="files"; filename="input.txt"

< ./input.txt
--boundary

### Add multiple images to product
POST {{host}}/products/1/images
Content-Type: multipart/form-data; boundary=boundary
Authorization: Bearer {{ accessToken }}

--boundary
Content-Disposition: form-data; name="files"; filename="input1.txt"

< ./input.txt
--boundary

--boundary
Content-Disposition: form-data; name="files"; filename="input2.txt"

< ./input.txt
--boundary





### Delete images from product
DELETE {{host}}/products/1/images
Content-Type: application/json
Authorization: Bearer {{ accessToken }}


### Creating a new product
POST {{host}}/products
Authorization: Bearer {{ accessToken }}
Content-Type: multipart/form-data; boundary=boundary


--boundary
Content-Disposition: form-data; name="name"

foobar
--boundary
Content-Disposition: form-data; name="description"


--boundary
Content-Disposition: form-data; name="price"

999
--boundary
Content-Disposition: form-data; name="stock"

10
--boundary
Content-Disposition: form-data; name="files"


--boundary

--boundary
Content-Disposition: form-data; name="category"

foobar
--boundary
